name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # Runs on push to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Make docs folder
        run: cd touch ./dist/my-angular-app/docs

      - name: Add .nojekyll file
        run: |
          cd ./dist/my-angular-app  # Replace <project-name> with your Angular project name
          touch .nojekyll
          ls -la  # List files to verify .nojekyll is present
    
      - name: List files in deployment folder
        run: ls -la ./dist/my-angular-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # No need to set manually for public repos
          publish_dir: ./dist/my-angular-app  # Change this to match your Angular output folder