name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Use Node.js 18 (or the version your Angular app requires)

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Angular app
      - name: Build Angular Project
        run: |
          npm run build -- --configuration production --base-href "https://jsonrohit.github.io/angular19-CI-CD/"
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"  # Increase memory limit for large projects

      # Step 5: Verify the build output
      - name: Verify Build Output
        run: ls -R dist

      # Step 6: Create .nojekyll file to disable Jekyll processing on GitHub Pages
      - name: Create .nojekyll file
        run: touch dist/my-angular-app/.nojekyll

      # Step 7: Install angular-cli-ghpages globally
      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/my-angular-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token for authentication