name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # Runs on push to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Create .nojekyll file
        run: touch dist/your-angular-project/.nojekyll

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/your-angular-project --no-silent

      - name: Make docs folder
        run: mkdir -p ./dist/my-angular-app/docs

      - name: Check if dist exists
        run: ls -la dist/your-angular-project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # No need to set manually for public repos
          publish_dir: ./dist/my-angular-app  # Change this to match your Angular output folder